---
- name: Create cloud-init directory
  file: path=/var/lib/coreos-install state=directory
  sudo: true

- name: Create coreos cloud config
  template: src=cloud-config.yml.j2 dest=/var/lib/coreos-install/user_data
  sudo: true

- name: Add InfluxDB service
  template: src=influxdb.service.j2 dest=/etc/systemd/system/influxdb.service
  sudo: true
