require 'fileutils'
require_relative 'config'

def provision_coreos_influxdb_vm(vm_number, config)
  vm_name = "influxdb-%02d" % vm_number
  config.vm.define vm_name do |config|
    config.vm.hostname = vm_name

    config.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 1
    end

    config.vm.network :private_network, ip: "172.17.8.#{vm_number+100}"
    config.vm.provision :file, :source => "cloud-config.yml", :destination => "/tmp/vagrantfile-user-data"
    config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "coreos-alpha"
  config.vm.box_version = ">= 308.0.1"
  config.vm.box_url = "http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

  (1..3).each do |vm_number|
    provision_coreos_influxdb_vm(vm_number, config)
  end
end
