#!/usr/bin/env bash

CONFIG_FILE="/etc/influxdb/config.toml"

if [ -n "${FORCE_HOSTNAME}" ]; then
  if [ "${FORCE_HOSTNAME}" == "auto" ]; then
    #set hostname with IPv4 eth0
    HOSTIPNAME=$(ip a show dev eth0 | grep inet | grep eth0 | sed -e 's/^.*inet.//g' -e 's/\/.*$//g')
    /usr/bin/perl -p -i -e "s/^# hostname.*$/hostname = \"${HOSTIPNAME}\"/g" ${CONFIG_FILE}
  else
    /usr/bin/perl -p -i -e "s/^# hostname.*$/hostname = \"${FORCE_HOSTNAME}\"/g" ${CONFIG_FILE}
  fi
fi

if [ -n "${SEEDS}" ]; then
  /usr/bin/perl -p -i -e "s/^# seed-servers.*$/seed-servers = [${SEEDS}]/g" ${CONFIG_FILE}
fi

if [ -n "${REPLI_FACTOR}" ]; then
  /usr/bin/perl -p -i -e "s/replication-factor = 1/replication-factor = ${REPLI_FACTOR}/g" ${CONFIG_FILE}
fi

if [ "${PRE_CREATE_DB}" == "**None**" ]; then
    unset PRE_CREATE_DB
fi

if [ "${SSL_CERT}" == "**None**" ]; then
    unset SSL_CERT
fi

API_URL="http://localhost:8086"
if [ -n "${SSL_CERT}" ]; then
    echo "=> Found ssl cert file, using ssl api instead"
    echo "=> Listening on port 8084(https api), disabling port 8086(http api)"
    echo -e "${SSL_CERT}" > /cert.pem
    sed -i -r -e 's/^# ssl-/ssl-/g' -e 's/^port *= * 8086/# port = 8086/' ${CONFIG_FILE}
    API_URL="https://localhost:8084"
fi

echo "=> Starting InfluxDB ..."

exec 2>&1
exec /usr/bin/influxdb -config=${CONFIG_FILE}
